#parameters:
#    datetimepicker.class: SC\DatetimepickerBundle\Form\Type\DatetimeType
#
#services:
#    stephanecollot.form.type.datetime:
#        class: "%datetimepicker.class%"
#        tags:
#            -  { name: form.type, alias: collot_datetime }

#service:
#    form.type.datePicker:
#        class: Acme\AcmeDemoBundle\Form\Type\DatePickerType
#        tags:
#          − { name: form.type, alias: datePicker }
 