parameters:
#    stephanecollot_datetimepicker.example.class: StephaneCollot\StephaneCollotDatetimepickerBundle\Example

services:
#    stephanecollot_datetimepicker.example:
#        class: %stephanecollot_datetimepicker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
