parameters:
    datetimepicker.class: StephaneCollot\DatetimepickerBundle\Form\Type\DatetimepickerType

services:
    stephanecollot.form.type.datetime:
        class: "%datetimepicker.class%"
        tags:
            -  { name: form.type, alias: collot_datetime }

#service:
#    form.type.datePicker:
#        class: Acme\AcmeDemoBundle\Form\Type\DatePickerType
#        tags:
#          − { name: form.type, alias: datePicker }
 