services:
    stephanecollot.form.type.datetime:
        class: StephaneCollot\StephaneCollotDatetimepickerBundle\Form\Type\DatetimepickerType
        tags:
            -  { name: form.type, alias: collot_datetime }

#service:
#    form.type.datePicker:
#        class: Acme\AcmeDemoBundle\Form\Type\DatePickerType
#        tags:
#          − { name: form.type, alias: datePicker }
 